export default {
	GET_CURR_LOCATION:"GET_CURR_LOCATION",
	GET_INPUT:"GET_INPUT",
	CHANGE_BETWEEN_BE_AND_WILL:"CHANGE_BETWEEN_BE_AND_WILL",
	GET_ADDRESS_FROM_GOOGLE:"GET_ADDRESS_FROM_GOOGLE",
	GET_SELECTED_ADDRESS:"GET_SELECTED_ADDRESS",
	GET_DISTANCE:"GET_DISTANCE",
	GET_PLACES_FROM_GOOGLE:"GET_PLACES_FROM_GOOGLE",
	GET_FARE:"GET_FARE"
};